# This file was generated by GoReleaser. DO NOT EDIT.
cask "shadowbox" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "edea19f40c14065cf70086e8443f82fffdf2222db5ddbaaf7f8256531a8c2db6"
      url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "8b387c3be073976623fba74664bb7a1dc82ae2b58c346078b4538fd9bd38fce2"
      url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2927960296638cc819151ac7ff1213b10f9fbdff7edb7e9cb0398dbeef3c33af"
      url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "24cfac6c08e690e9925bffcc4d325bd1cffe9d93a1f53a30e49b14f8faed59d9"
      url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-linux-arm64.tar.gz"
    end
  end

  name "shadowbox"
  desc "Music acquisition CLI for YouTube and Bandcamp"
  homepage "https://github.com/EnJulian/shadowbox"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "yt-dlp",
    ]

  binary "shadowbox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shadowbox"]
    end
  end

  # No zap stanza required

end
