# This file was generated by GoReleaser. DO NOT EDIT.
cask "shadowbox" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "3b68e32b293f83d9a6126d937748aa0ffe885c1135a38e80188c0b6f75924c95"
      url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "cb884c80dacf0c748825e39534637135e94d705e3689ff3de049b4887e44a7c0"
      url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e8e38a0b4be6bf3057f63551e6feb982c60ee43067c4982db3d32c8200e746df"
      url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "1db07e6837fbb6e315dafaeb8bdabf614faf3d42903d828c815c5bfe3124de6a"
      url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-linux-arm64.tar.gz"
    end
  end

  name "shadowbox"
  desc "Music acquisition CLI for YouTube and Bandcamp"
  homepage "https://github.com/EnJulian/shadowbox"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "yt-dlp",
    ]

  binary "shadowbox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shadowbox"]
    end
  end

  # No zap stanza required

end
