# This file was generated by GoReleaser. DO NOT EDIT.
cask "shadowbox" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "0bbbedb06d36ead143106b11e26d3ea6d954f97e8cf8070567759144217f49bf"
      url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "0a216f3d20afb0c6c8176f9411bdc4ab2b3cf1a368878a0b73de4e114489d8b0"
      url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6dfb9b4c5fc8b3f7078d1a28525d430cfa1de20faa0a1157230472bc9bd5a5a2"
      url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "b9481432cd01ba2014845181d24a2add2810e3115475346a76518d02e3e9232b"
      url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-linux-arm64.tar.gz"
    end
  end

  name "shadowbox"
  desc "Music acquisition CLI for YouTube and Bandcamp"
  homepage "https://github.com/EnJulian/shadowbox"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "yt-dlp",
    ]

  binary "shadowbox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shadowbox"]
    end
  end

  # No zap stanza required

end
